{% set name = "lbenv" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b849d59f9b16e2790a008d13a196a16394a4fa847ca8829ef273a5b2d6561d6a

build:
  entry_points:
    - lb-run = LbEnv.ProjectEnv.script:main
    - lb-completion-helper = LbEnv.Utils.Completion:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - lbplatformutils >=4.2.3
    - xenv <1.0.0
    - importlib-resources
    - importlib-metadata

test:
  imports:
    - LbEnv
    - LbEnv.ProjectEnv
    - LbEnv.Utils
  commands:
    - pip check
    - lb-run --help
    - lb-completion-helper --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.cern.ch/lhcb-core/LbEnv
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: LHCb Environment tools
  doc_url: https://gitlab.cern.ch/lhcb-core/LbEnv
  dev_url: https://gitlab.cern.ch/lhcb-core/LbEnv

extra:
  recipe-maintainers:
    - chrisburr
