{% set name = "LbEnv" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd92a3731e212df0a547bb6a33ce5a24188805c9c97b662974195e88c5ef31b2

build:
  number: 0
  # Can't be noarch due to use of 2to3 in setup.py
  # noarch: python
  entry_points:
    - lb-run=LbEnv.ProjectEnv.script:main
    - lb-completion-helper=LbEnv.Utils.Completion:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm
    - nose
  run:
    - lbplatformutils >=4.2.3
    - python
    - setuptools
    - six
    - xenv <1.0.0

test:
  imports:
    - LbEnv
    - LbEnv.ProjectEnv
    - LbEnv.Utils
  commands:
    - lb-run --help
    - lb-completion-helper --help

about:
  home: https://gitlab.cern.ch/lhcb-core/LbEnv
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: LHCb Environment tools
  doc_url: https://gitlab.cern.ch/lhcb-core/LbEnv
  dev_url: https://gitlab.cern.ch/lhcb-core/LbEnv

extra:
  recipe-maintainers:
    - chrisburr
